# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/keiserb/rosstacks/youbot_hardware/youbot_driver_rtt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/keiserb/rosstacks/youbot_hardware/youbot_driver_rtt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keiserb/rosstacks/youbot_hardware/youbot_driver_rtt/CMakeFiles /home/keiserb/rosstacks/youbot_hardware/youbot_driver_rtt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keiserb/rosstacks/youbot_hardware/youbot_driver_rtt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ROSBUILD_genmsg_cpp

# Build rule for target.
ROSBUILD_genmsg_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_genmsg_cpp
.PHONY : ROSBUILD_genmsg_cpp

# fast build rule for target.
ROSBUILD_genmsg_cpp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_genmsg_cpp.dir/build.make CMakeFiles/ROSBUILD_genmsg_cpp.dir/build
.PHONY : ROSBUILD_genmsg_cpp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_genmsg_lisp

# Build rule for target.
ROSBUILD_genmsg_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_genmsg_lisp
.PHONY : ROSBUILD_genmsg_lisp

# fast build rule for target.
ROSBUILD_genmsg_lisp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_genmsg_lisp.dir/build.make CMakeFiles/ROSBUILD_genmsg_lisp.dir/build
.PHONY : ROSBUILD_genmsg_lisp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_gensrv_cpp

# Build rule for target.
ROSBUILD_gensrv_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_gensrv_cpp
.PHONY : ROSBUILD_gensrv_cpp

# fast build rule for target.
ROSBUILD_gensrv_cpp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_gensrv_cpp.dir/build.make CMakeFiles/ROSBUILD_gensrv_cpp.dir/build
.PHONY : ROSBUILD_gensrv_cpp/fast

#=============================================================================
# Target rules for targets named ROSBUILD_gensrv_lisp

# Build rule for target.
ROSBUILD_gensrv_lisp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ROSBUILD_gensrv_lisp
.PHONY : ROSBUILD_gensrv_lisp

# fast build rule for target.
ROSBUILD_gensrv_lisp/fast:
	$(MAKE) -f CMakeFiles/ROSBUILD_gensrv_lisp.dir/build.make CMakeFiles/ROSBUILD_gensrv_lisp.dir/build
.PHONY : ROSBUILD_gensrv_lisp/fast

#=============================================================================
# Target rules for targets named clean-test-results

# Build rule for target.
clean-test-results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-test-results
.PHONY : clean-test-results

# fast build rule for target.
clean-test-results/fast:
	$(MAKE) -f CMakeFiles/clean-test-results.dir/build.make CMakeFiles/clean-test-results.dir/build
.PHONY : clean-test-results/fast

#=============================================================================
# Target rules for targets named rosbuild_precompile

# Build rule for target.
rosbuild_precompile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosbuild_precompile
.PHONY : rosbuild_precompile

# fast build rule for target.
rosbuild_precompile/fast:
	$(MAKE) -f CMakeFiles/rosbuild_precompile.dir/build.make CMakeFiles/rosbuild_precompile.dir/build
.PHONY : rosbuild_precompile/fast

#=============================================================================
# Target rules for targets named rosbuild_premsgsrvgen

# Build rule for target.
rosbuild_premsgsrvgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosbuild_premsgsrvgen
.PHONY : rosbuild_premsgsrvgen

# fast build rule for target.
rosbuild_premsgsrvgen/fast:
	$(MAKE) -f CMakeFiles/rosbuild_premsgsrvgen.dir/build.make CMakeFiles/rosbuild_premsgsrvgen.dir/build
.PHONY : rosbuild_premsgsrvgen/fast

#=============================================================================
# Target rules for targets named rospack_genmsg

# Build rule for target.
rospack_genmsg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_genmsg
.PHONY : rospack_genmsg

# fast build rule for target.
rospack_genmsg/fast:
	$(MAKE) -f CMakeFiles/rospack_genmsg.dir/build.make CMakeFiles/rospack_genmsg.dir/build
.PHONY : rospack_genmsg/fast

#=============================================================================
# Target rules for targets named rospack_genmsg_libexe

# Build rule for target.
rospack_genmsg_libexe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_genmsg_libexe
.PHONY : rospack_genmsg_libexe

# fast build rule for target.
rospack_genmsg_libexe/fast:
	$(MAKE) -f CMakeFiles/rospack_genmsg_libexe.dir/build.make CMakeFiles/rospack_genmsg_libexe.dir/build
.PHONY : rospack_genmsg_libexe/fast

#=============================================================================
# Target rules for targets named rospack_gensrv

# Build rule for target.
rospack_gensrv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rospack_gensrv
.PHONY : rospack_gensrv

# fast build rule for target.
rospack_gensrv/fast:
	$(MAKE) -f CMakeFiles/rospack_gensrv.dir/build.make CMakeFiles/rospack_gensrv.dir/build
.PHONY : rospack_gensrv/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test-future

# Build rule for target.
test-future: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-future
.PHONY : test-future

# fast build rule for target.
test-future/fast:
	$(MAKE) -f CMakeFiles/test-future.dir/build.make CMakeFiles/test-future.dir/build
.PHONY : test-future/fast

#=============================================================================
# Target rules for targets named test-results

# Build rule for target.
test-results: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-results
.PHONY : test-results

# fast build rule for target.
test-results/fast:
	$(MAKE) -f CMakeFiles/test-results.dir/build.make CMakeFiles/test-results.dir/build
.PHONY : test-results/fast

#=============================================================================
# Target rules for targets named test-results-run

# Build rule for target.
test-results-run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-results-run
.PHONY : test-results-run

# fast build rule for target.
test-results-run/fast:
	$(MAKE) -f CMakeFiles/test-results-run.dir/build.make CMakeFiles/test-results-run.dir/build
.PHONY : test-results-run/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named youbot-plugin

# Build rule for target.
youbot-plugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 youbot-plugin
.PHONY : youbot-plugin

# fast build rule for target.
youbot-plugin/fast:
	$(MAKE) -f CMakeFiles/youbot-plugin.dir/build.make CMakeFiles/youbot-plugin.dir/build
.PHONY : youbot-plugin/fast

#=============================================================================
# Target rules for targets named youbot_driver_rtt

# Build rule for target.
youbot_driver_rtt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 youbot_driver_rtt
.PHONY : youbot_driver_rtt

# fast build rule for target.
youbot_driver_rtt/fast:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/build
.PHONY : youbot_driver_rtt/fast

# target to build an object file
src/youbot_arm_service.o:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/src/youbot_arm_service.o
.PHONY : src/youbot_arm_service.o

# target to preprocess a source file
src/youbot_arm_service.i:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/src/youbot_arm_service.i
.PHONY : src/youbot_arm_service.i

# target to generate assembly for a file
src/youbot_arm_service.s:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/src/youbot_arm_service.s
.PHONY : src/youbot_arm_service.s

# target to build an object file
src/youbot_base_service.o:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/src/youbot_base_service.o
.PHONY : src/youbot_base_service.o

# target to preprocess a source file
src/youbot_base_service.i:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/src/youbot_base_service.i
.PHONY : src/youbot_base_service.i

# target to generate assembly for a file
src/youbot_base_service.s:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/src/youbot_base_service.s
.PHONY : src/youbot_base_service.s

# target to build an object file
src/youbot_driver_component.o:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/src/youbot_driver_component.o
.PHONY : src/youbot_driver_component.o

# target to preprocess a source file
src/youbot_driver_component.i:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/src/youbot_driver_component.i
.PHONY : src/youbot_driver_component.i

# target to generate assembly for a file
src/youbot_driver_component.s:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/src/youbot_driver_component.s
.PHONY : src/youbot_driver_component.s

# target to build an object file
src/youbot_helpers.o:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/src/youbot_helpers.o
.PHONY : src/youbot_helpers.o

# target to preprocess a source file
src/youbot_helpers.i:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/src/youbot_helpers.i
.PHONY : src/youbot_helpers.i

# target to generate assembly for a file
src/youbot_helpers.s:
	$(MAKE) -f CMakeFiles/youbot_driver_rtt.dir/build.make CMakeFiles/youbot_driver_rtt.dir/src/youbot_helpers.s
.PHONY : src/youbot_helpers.s

# target to build an object file
src/youbot_plugin.o:
	$(MAKE) -f CMakeFiles/youbot-plugin.dir/build.make CMakeFiles/youbot-plugin.dir/src/youbot_plugin.o
.PHONY : src/youbot_plugin.o

# target to preprocess a source file
src/youbot_plugin.i:
	$(MAKE) -f CMakeFiles/youbot-plugin.dir/build.make CMakeFiles/youbot-plugin.dir/src/youbot_plugin.i
.PHONY : src/youbot_plugin.i

# target to generate assembly for a file
src/youbot_plugin.s:
	$(MAKE) -f CMakeFiles/youbot-plugin.dir/build.make CMakeFiles/youbot-plugin.dir/src/youbot_plugin.s
.PHONY : src/youbot_plugin.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ROSBUILD_genmsg_cpp"
	@echo "... ROSBUILD_genmsg_lisp"
	@echo "... ROSBUILD_gensrv_cpp"
	@echo "... ROSBUILD_gensrv_lisp"
	@echo "... clean-test-results"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... rosbuild_precompile"
	@echo "... rosbuild_premsgsrvgen"
	@echo "... rospack_genmsg"
	@echo "... rospack_genmsg_libexe"
	@echo "... rospack_gensrv"
	@echo "... test"
	@echo "... test-future"
	@echo "... test-results"
	@echo "... test-results-run"
	@echo "... tests"
	@echo "... uninstall"
	@echo "... youbot-plugin"
	@echo "... youbot_driver_rtt"
	@echo "... src/youbot_arm_service.o"
	@echo "... src/youbot_arm_service.i"
	@echo "... src/youbot_arm_service.s"
	@echo "... src/youbot_base_service.o"
	@echo "... src/youbot_base_service.i"
	@echo "... src/youbot_base_service.s"
	@echo "... src/youbot_driver_component.o"
	@echo "... src/youbot_driver_component.i"
	@echo "... src/youbot_driver_component.s"
	@echo "... src/youbot_helpers.o"
	@echo "... src/youbot_helpers.i"
	@echo "... src/youbot_helpers.s"
	@echo "... src/youbot_plugin.o"
	@echo "... src/youbot_plugin.i"
	@echo "... src/youbot_plugin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

